//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int ModelId { get; set; }
        public string ModelName { get; set; }
        public Nullable<decimal> ModelPrice { get; set; }
        public string ModelColor { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public Nullable<int> MarkaId { get; set; }
    
        public virtual Mark Mark { get; set; }
    }
}
