//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int StudentId { get; set; }
        public int GroupId { get; set; }
        public string StudentName { get; set; }
        public string StudentSurname { get; set; }
        public Nullable<System.DateTime> StudentBirthDate { get; set; }
        public string StudentEmail { get; set; }
        public string StudentPhone { get; set; }
        public Nullable<System.DateTime> StudentRegistrationDate { get; set; }
        public string StudentPhoto { get; set; }
    
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
